"""
HTTPS Date-header time source for sink-side Gatherlink time fallback.

This is not a replacement for NTP or NTS. It exists as a constrained fallback
for environments where UDP/123 is blocked but outbound HTTPS is available. The
result is intentionally labeled as ``https-date`` so monitor and policy code can
show that it is lower-confidence than direct NTP.
"""

from __future__ import annotations

import time
import urllib.error
import urllib.request
from email.utils import parsedate_to_datetime

from gatherlink.shared.logging import get_logger
from gatherlink.time.sources.direct_ntp import DirectNtpSample

logger = get_logger(__name__)

HTTPS_TIME_TIMEOUT_SECONDS = 1.5


def query_https_date_time(url: str, *, timeout_seconds: float = HTTPS_TIME_TIMEOUT_SECONDS) -> DirectNtpSample | None:
    """
    Read a coarse wall-clock sample from an HTTPS ``Date`` response header.

    HTTP dates are only second-resolution and may be generated by an edge proxy.
    We still compute RTT/offset with the same shape as direct NTP so downstream
    sink-time code can stay simple while keeping the source visible.
    """
    request = urllib.request.Request(url, method="HEAD")
    origin_unix_us = time.time_ns() // 1000
    origin_monotonic_us = time.monotonic_ns() // 1000
    try:
        with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
            date_header = response.headers.get("Date")
    except (OSError, urllib.error.URLError, TimeoutError):
        logger.debug("HTTPS time query failed", extra={"url": url})
        return None
    destination_monotonic_us = time.monotonic_ns() // 1000
    destination_unix_us = time.time_ns() // 1000
    if not date_header:
        logger.debug("HTTPS time response did not include Date", extra={"url": url})
        return None
    try:
        server_unix_us = int(parsedate_to_datetime(date_header).timestamp() * 1_000_000)
    except (TypeError, ValueError, OverflowError):
        logger.debug("HTTPS time Date header was not parseable", extra={"url": url, "date": date_header})
        return None
    rtt_us = max(destination_monotonic_us - origin_monotonic_us, 0)
    corrected_unix_us = server_unix_us + (rtt_us // 2)
    midpoint_local_unix_us = origin_unix_us + ((destination_unix_us - origin_unix_us) // 2)
    return DirectNtpSample(
        server=url,
        unix_us=corrected_unix_us,
        received_monotonic_us=destination_monotonic_us,
        offset_us=corrected_unix_us - midpoint_local_unix_us,
        rtt_us=rtt_us,
        stratum=None,
        source="https-date",
    )
